import { useMemo, useState } from 'react'
import { Activity, KeyRound, Mail, MapPin, Pencil, Plus, Search, Shield, ShieldCheck, Trash2, UserCog, Users } from 'lucide-react'
import { PageContainer, PageHeader } from '@/shared/components/layouts'
import { Button } from '@/shared/components/ui/button'
import { Input } from '@/shared/components/ui/input'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/shared/components/ui/dialog'
import { Skeleton } from '@/shared/components/ui/skeleton'
import { useEmployeesStore } from '@/features/employees/hooks/use-employees-store'
import { EmployeeFormModal } from '@/features/employees/components/employee-form-modal'
import { employeeFullName, employeeInitials, type Employee, type EmployeeFormData } from '@/features/employees/types/employee.types'

interface InviteDraft { firstName: string; lastName: string; email: string; phone: string; jobTitle: string; location: string }
const EMPTY_INVITE: InviteDraft = { firstName: '', lastName: '', email: '', phone: '', jobTitle: 'HR Administrator', location: 'Karachi' }

export function AdminManagementPage() {
  const store = useEmployeesStore()
  const [query, setQuery] = useState('')
  const [inviteOpen, setInviteOpen] = useState(false)
  const [invite, setInvite] = useState(EMPTY_INVITE)
  const [confirmRemove, setConfirmRemove] = useState<Employee | null>(null)
  const admins = useMemo(() => store.employees.filter((employee) => employee.role === 'admin' && `${employeeFullName(employee)} ${employee.email} ${employee.department}`.toLowerCase().includes(query.toLowerCase())), [query, store.employees])

  const createAdmin = async () => {
    const data: EmployeeFormData = { ...invite, role: 'admin', department: 'Human Resources', status: 'active', joinDate: new Date().toISOString().split('T')[0] }
    await store.createEmployee(data)
    setInviteOpen(false)
    setInvite(EMPTY_INVITE)
  }

  return (
    <PageContainer>
      <PageHeader title="Admin Management" description="Create and govern HR administrator accounts. Super Admin access only." actions={<Button onClick={() => setInviteOpen(true)}><Plus className="size-4" /> Add administrator</Button>} />
      <div className="mb-4 grid grid-cols-2 gap-2.5 lg:grid-cols-4">{[{ icon: ShieldCheck, value: admins.length, label: 'HR administrators', hint: 'Active privileged accounts' }, { icon: Users, value: store.employees.length, label: 'Directory accounts', hint: 'All workspace members' }, { icon: KeyRound, value: '2', label: 'Admin permissions', hint: 'Create and remove admins' }, { icon: Activity, value: 'Healthy', label: 'Access status', hint: 'No policy violations' }].map((stat) => { const Icon = stat.icon; return <div key={stat.label} className="flex items-center gap-3 rounded-2xl border border-[var(--dw-color-border-default)] bg-[var(--dw-color-surface-base)] p-3.5 shadow-[var(--dw-shadow-xs)]"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-violet-50 text-violet-600"><Icon className="size-[18px]" /></span><div className="min-w-0"><p className="text-lg font-black text-[var(--dw-color-ink-primary)]">{stat.value}</p><p className="truncate text-[11px] font-semibold text-[var(--dw-color-ink-secondary)]">{stat.label}</p><p className="truncate text-[9px] text-[var(--dw-color-ink-tertiary)]">{stat.hint}</p></div></div> })}</div>
      <div className="mb-4 rounded-2xl border border-amber-200 bg-amber-50 p-4"><p className="flex items-center gap-2 text-sm font-bold text-amber-800"><Shield className="size-4" /> Privileged access boundary</p><p className="mt-1 text-xs leading-relaxed text-amber-700">Administrators can manage employees, attendance, reports, documents, and organization settings. Only the seeded Super Admin can create or remove administrator accounts.</p></div>
      <div className="overflow-hidden rounded-2xl border border-[var(--dw-color-border-default)] bg-[var(--dw-color-surface-base)] shadow-[var(--dw-shadow-sm)]"><div className="flex flex-col gap-3 border-b border-[var(--dw-color-border-default)] p-3 sm:flex-row sm:items-center"><div><h2 className="text-sm font-bold text-[var(--dw-color-ink-primary)]">Administrator accounts</h2><p className="text-[10px] text-[var(--dw-color-ink-tertiary)]">{admins.length} account{admins.length === 1 ? '' : 's'}</p></div><div className="relative sm:ml-auto sm:w-72"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-[var(--dw-color-ink-tertiary)]" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search administrators…" className="pl-9" /></div></div>
        {store.isLoading ? <div className="space-y-2 p-4">{[1,2].map((item) => <Skeleton key={item} className="h-16 rounded-xl" />)}</div> : <div className="divide-y divide-[var(--dw-color-border-default)]">{admins.map((admin) => <div key={admin.id} className="group flex flex-col gap-3 p-4 sm:flex-row sm:items-center"><span className="flex size-11 shrink-0 items-center justify-center rounded-xl text-sm font-bold text-white" style={{ background: admin.avatarColor }}>{employeeInitials(admin)}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-bold text-[var(--dw-color-ink-primary)]">{employeeFullName(admin)}</p><span className="rounded-full border border-violet-200 bg-violet-50 px-2 py-0.5 text-[9px] font-bold text-violet-700">HR ADMIN</span><span className="rounded-full border border-emerald-200 bg-emerald-50 px-2 py-0.5 text-[9px] font-bold text-emerald-700">ACTIVE</span></div><p className="mt-1 flex flex-wrap gap-x-3 gap-y-1 text-[10px] text-[var(--dw-color-ink-tertiary)]"><span className="flex items-center gap-1"><Mail className="size-3" />{admin.email}</span><span className="flex items-center gap-1"><MapPin className="size-3" />{admin.location}</span><span>{admin.jobTitle}</span></p></div><div className="flex items-center gap-2"><Button variant="ghost" size="sm" onClick={() => store.openEditForm(admin)}><Pencil className="size-3.5" /> Edit</Button><Button variant="danger-outline" size="sm" onClick={() => setConfirmRemove(admin)}><Trash2 className="size-3.5" /> Remove</Button></div></div>)}</div>}
      </div>

      <Dialog open={inviteOpen} onOpenChange={setInviteOpen}><DialogContent className="max-w-lg"><DialogHeader><DialogTitle>Add HR administrator</DialogTitle><DialogDescription>Create a privileged account for a trusted people-operations administrator.</DialogDescription></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><label className="space-y-1.5 text-xs font-semibold text-[var(--dw-color-ink-secondary)]">First name<Input value={invite.firstName} onChange={(event) => setInvite({ ...invite, firstName: event.target.value })} /></label><label className="space-y-1.5 text-xs font-semibold text-[var(--dw-color-ink-secondary)]">Last name<Input value={invite.lastName} onChange={(event) => setInvite({ ...invite, lastName: event.target.value })} /></label><label className="space-y-1.5 text-xs font-semibold text-[var(--dw-color-ink-secondary)] sm:col-span-2">Work email<Input type="email" value={invite.email} onChange={(event) => setInvite({ ...invite, email: event.target.value })} placeholder="admin@dreamweavers.com" /></label><label className="space-y-1.5 text-xs font-semibold text-[var(--dw-color-ink-secondary)]">Phone<Input value={invite.phone} onChange={(event) => setInvite({ ...invite, phone: event.target.value })} placeholder="+92 300 0000000" /></label><label className="space-y-1.5 text-xs font-semibold text-[var(--dw-color-ink-secondary)]">Location<Input value={invite.location} onChange={(event) => setInvite({ ...invite, location: event.target.value })} /></label><label className="space-y-1.5 text-xs font-semibold text-[var(--dw-color-ink-secondary)] sm:col-span-2">Job title<Input value={invite.jobTitle} onChange={(event) => setInvite({ ...invite, jobTitle: event.target.value })} /></label></div><div className="rounded-xl border border-violet-200 bg-violet-50 p-3 text-xs text-violet-700"><UserCog className="mr-1.5 inline size-4" />This account receives HR administration permissions. Super Admin access cannot be created here.</div><DialogFooter><Button variant="ghost" onClick={() => setInviteOpen(false)}>Cancel</Button><Button onClick={() => void createAdmin()} disabled={!invite.firstName.trim() || !invite.lastName.trim() || !invite.email.includes('@')} loading={store.isSaving}><ShieldCheck className="size-4" /> Create administrator</Button></DialogFooter></DialogContent></Dialog>
      <Dialog open={Boolean(confirmRemove)} onOpenChange={(open) => !open && setConfirmRemove(null)}><DialogContent><DialogHeader><DialogTitle>Remove administrator access?</DialogTitle><DialogDescription>{confirmRemove ? `${employeeFullName(confirmRemove)} will be removed from the directory and lose all HR administration access.` : ''}</DialogDescription></DialogHeader><DialogFooter><Button variant="ghost" onClick={() => setConfirmRemove(null)}>Cancel</Button><Button variant="danger" onClick={() => { if (confirmRemove) void store.deleteEmployee(confirmRemove); setConfirmRemove(null) }}><Trash2 className="size-4" /> Remove administrator</Button></DialogFooter></DialogContent></Dialog>
      <EmployeeFormModal open={store.isFormOpen} onClose={store.closeForm} editingEmployee={store.editingEmployee} assignableRoles={['admin']} isSaving={store.isSaving} onSubmit={(data) => { if (store.editingEmployee) void store.updateEmployee(store.editingEmployee.id, { ...data, role: 'admin' }) }} />
    </PageContainer>
  )
}
