import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { Activity, ArrowLeft, CalendarDays, Check, CheckCircle2, Clock3, Edit3, FileText, MessageSquare, Paperclip, Send, Tag, Trash2, UserRound } from 'lucide-react'
import { PageContainer } from '@/shared/components/layouts'
import { Button } from '@/shared/components/ui/button'
import { Skeleton } from '@/shared/components/ui/skeleton'
import { ErrorState } from '@/shared/components/premium'
import { cn } from '@/shared/lib/utils'
import { useAuth } from '@/shared/hooks/use-auth'
import { useCalendarStore } from '@/features/calendar/hooks/use-calendar-store'
import { TaskFormModal } from '@/features/calendar/components/task-form-modal'
import { getPerson } from '@/features/calendar/data/calendar.mock'
import { PRIORITY_CONFIG, STATUS_CONFIG } from '@/features/calendar/types/calendar.types'

interface Subtask { id: string; title: string; done: boolean }

export function TaskDetailPage() {
  const { id } = useParams()
  const navigate = useNavigate()
  const { can } = useAuth()
  const store = useCalendarStore()
  const [comment, setComment] = useState('')
  const [subtaskText, setSubtaskText] = useState('')
  const [subtasks, setSubtasks] = useState<Subtask[]>([])
  const task = store.tasks.find((item) => item.id === id)

  useEffect(() => { if (!id) return; try { setSubtasks(JSON.parse(localStorage.getItem(`dw_subtasks_${id}`) ?? '[]') as Subtask[]) } catch { setSubtasks([]) } }, [id])
  const saveSubtasks = (next: Subtask[]) => { setSubtasks(next); if (id) localStorage.setItem(`dw_subtasks_${id}`, JSON.stringify(next)) }

  if (store.isLoading) return <PageContainer><Skeleton className="h-16 rounded-xl" /><div className="mt-4 grid gap-4 lg:grid-cols-[1fr_340px]"><Skeleton className="h-[640px] rounded-2xl" /><Skeleton className="h-[540px] rounded-2xl" /></div></PageContainer>
  const canRead = task && (store.perms.canViewTask(task) || can('tasks:read_all'))
  if (!task || !canRead) return <PageContainer><ErrorState title="Task not found" description="This task may have been removed or is outside your access scope." action={<Button onClick={() => navigate('/tasks')}><ArrowLeft className="size-4" /> Back to tasks</Button>} /></PageContainer>

  const assignee = getPerson(task.assignedToId)
  const assigner = getPerson(task.assignedById)
  const reviewer = task.reviewerId ? getPerson(task.reviewerId) : null
  const status = STATUS_CONFIG[task.status]
  const priority = PRIORITY_CONFIG[task.priority]
  const completedSubtasks = subtasks.filter((item) => item.done).length

  const postComment = async () => { const value = comment.trim(); if (!value) return; await store.addComment(task.id, value); setComment('') }

  return (
    <PageContainer>
      <div className="mb-4 flex flex-wrap items-center justify-between gap-3"><button type="button" onClick={() => navigate('/tasks')} className="flex items-center gap-1.5 text-xs font-semibold text-[var(--dw-color-ink-tertiary)] hover:text-[var(--dw-color-brand-primary)]"><ArrowLeft className="size-4" /> Back to Tasks</button><div className="flex gap-2">{store.perms.canEditTask(task) && <Button variant="secondary" size="sm" onClick={() => store.openEditForm(task)}><Edit3 className="size-4" /> Edit</Button>}{store.perms.canDeleteTask(task) && <Button variant="danger-outline" size="sm" onClick={() => { if (window.confirm('Delete this task permanently?')) { void store.deleteTask(task.id); navigate('/tasks') } }}><Trash2 className="size-4" /> Delete</Button>}</div></div>
      <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_340px]">
        <main className="min-w-0 space-y-4">
          <section className="rounded-2xl border border-[var(--dw-color-border-default)] bg-[var(--dw-color-surface-base)] p-4 shadow-[var(--dw-shadow-sm)] sm:p-6"><div className="flex flex-wrap gap-2"><span className={cn('rounded-full px-2.5 py-1 text-[10px] font-bold', status.bg, status.color)}>{status.icon} {status.label}</span><span className={cn('rounded-full border px-2.5 py-1 text-[10px] font-bold', priority.bg, priority.border, priority.color)}><span className={cn('mr-1 inline-block size-1.5 rounded-full', priority.dot)} />{priority.label}</span></div><h1 className="mt-4 text-2xl font-black leading-tight text-[var(--dw-color-ink-primary)]">{task.title}</h1><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-[var(--dw-color-ink-secondary)]">{task.description}</p><div className="mt-4 flex flex-wrap gap-1.5">{task.labels.map((label) => <span key={label} className="flex items-center gap-1 rounded-full bg-[var(--dw-color-surface-sunken)] px-2.5 py-1 text-[10px] font-semibold text-[var(--dw-color-ink-tertiary)]"><Tag className="size-3" />{label}</span>)}</div></section>

          <section className="rounded-2xl border border-[var(--dw-color-border-default)] bg-[var(--dw-color-surface-base)] p-4 shadow-[var(--dw-shadow-sm)]"><div className="flex items-center justify-between"><div><h2 className="flex items-center gap-2 text-sm font-bold text-[var(--dw-color-ink-primary)]"><CheckCircle2 className="size-4 text-[var(--dw-color-brand-primary)]" /> Subtasks</h2><p className="mt-0.5 text-[10px] text-[var(--dw-color-ink-tertiary)]">{completedSubtasks} of {subtasks.length} completed</p></div>{subtasks.length > 0 && <span className="text-xs font-bold text-[var(--dw-color-brand-primary)]">{Math.round(completedSubtasks / subtasks.length * 100)}%</span>}</div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-[var(--dw-color-border-default)]"><div className="h-full rounded-full bg-[var(--dw-color-brand-primary)] transition-all" style={{ width: `${subtasks.length ? completedSubtasks / subtasks.length * 100 : 0}%` }} /></div><div className="mt-3 space-y-1.5">{subtasks.map((item) => <div key={item.id} className="group flex items-center gap-2 rounded-lg p-2 hover:bg-[var(--dw-color-surface-sunken)]"><button type="button" onClick={() => saveSubtasks(subtasks.map((entry) => entry.id === item.id ? { ...entry, done: !entry.done } : entry))} className={cn('flex size-5 items-center justify-center rounded-md border', item.done ? 'border-[var(--dw-color-brand-primary)] bg-[var(--dw-color-brand-primary)] text-white' : 'border-[var(--dw-color-border-strong)]')}>{item.done && <Check className="size-3" />}</button><span className={cn('flex-1 text-xs text-[var(--dw-color-ink-secondary)]', item.done && 'line-through opacity-60')}>{item.title}</span><button type="button" onClick={() => saveSubtasks(subtasks.filter((entry) => entry.id !== item.id))} className="opacity-0 group-hover:opacity-100"><Trash2 className="size-3.5 text-red-400" /></button></div>)}</div><form className="mt-3 flex gap-2" onSubmit={(event) => { event.preventDefault(); const title = subtaskText.trim(); if (!title) return; saveSubtasks([...subtasks, { id: `sub_${Date.now()}`, title, done: false }]); setSubtaskText('') }}><input value={subtaskText} onChange={(event) => setSubtaskText(event.target.value)} placeholder="Add a subtask…" className="h-9 min-w-0 flex-1 rounded-lg border border-[var(--dw-color-border-default)] bg-[var(--dw-color-surface-sunken)] px-3 text-xs text-[var(--dw-color-ink-primary)] outline-none focus:border-[var(--dw-color-brand-primary)]" /><Button type="submit" size="sm">Add</Button></form></section>

          <section className="rounded-2xl border border-[var(--dw-color-border-default)] bg-[var(--dw-color-surface-base)] p-4 shadow-[var(--dw-shadow-sm)]"><h2 className="flex items-center gap-2 text-sm font-bold text-[var(--dw-color-ink-primary)]"><MessageSquare className="size-4 text-[var(--dw-color-brand-primary)]" /> Comments <span className="text-[10px] font-normal text-[var(--dw-color-ink-tertiary)]">{task.comments.length}</span></h2><div className="mt-4 space-y-4">{task.comments.map((item) => <div key={item.id} className="flex gap-3"><span className="flex size-8 shrink-0 items-center justify-center rounded-full text-[10px] font-bold text-white" style={{ background: item.authorColor }}>{item.authorInitials}</span><div className="min-w-0 flex-1 rounded-xl bg-[var(--dw-color-surface-sunken)] p-3"><div className="flex items-center justify-between gap-2"><p className="text-xs font-bold text-[var(--dw-color-ink-primary)]">{item.authorName}</p><p className="text-[9px] text-[var(--dw-color-ink-tertiary)]">{new Date(item.createdAt).toLocaleDateString('en-PK', { dateStyle: 'medium' })}</p></div><p className="mt-1 text-xs leading-relaxed text-[var(--dw-color-ink-secondary)]">{item.content}</p></div></div>)}</div><div className="mt-4 flex gap-2"><textarea value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Add a comment…" className="min-h-20 min-w-0 flex-1 resize-none rounded-xl border border-[var(--dw-color-border-default)] bg-[var(--dw-color-surface-sunken)] p-3 text-xs text-[var(--dw-color-ink-primary)] outline-none focus:border-[var(--dw-color-brand-primary)]" /><Button size="icon" onClick={() => void postComment()} disabled={!comment.trim()} aria-label="Post comment"><Send className="size-4" /></Button></div></section>
        </main>

        <aside className="h-fit space-y-4 lg:sticky lg:top-24"><section className="rounded-2xl border border-[var(--dw-color-border-default)] bg-[var(--dw-color-surface-base)] p-4 shadow-[var(--dw-shadow-sm)]"><h2 className="text-xs font-bold uppercase tracking-wider text-[var(--dw-color-ink-tertiary)]">Task details</h2><div className="mt-3 space-y-3">{[{ icon: UserRound, label: 'Assignee', value: assignee?.name ?? 'Unassigned' }, { icon: CalendarDays, label: 'Due date', value: new Date(task.dueDate).toLocaleDateString('en-PK', { dateStyle: 'medium' }) }, { icon: Clock3, label: 'Estimate', value: `${task.estimatedHours} hours` }, { icon: UserRound, label: 'Assigned by', value: assigner?.name ?? 'Unknown' }, { icon: CheckCircle2, label: 'Reviewer', value: reviewer?.name ?? 'Not assigned' }].map((item) => { const Icon = item.icon; return <div key={item.label} className="flex items-center gap-3"><span className="flex size-8 shrink-0 items-center justify-center rounded-lg bg-[var(--dw-color-surface-sunken)]"><Icon className="size-4 text-[var(--dw-color-ink-tertiary)]" /></span><div><p className="text-[9px] uppercase tracking-wide text-[var(--dw-color-ink-tertiary)]">{item.label}</p><p className="text-xs font-semibold text-[var(--dw-color-ink-primary)]">{item.value}</p></div></div> })}</div><div className="mt-4"><div className="flex justify-between text-[10px] font-semibold text-[var(--dw-color-ink-secondary)]"><span>Progress</span><span>{task.completionPercent}%</span></div><input type="range" min="0" max="100" step="5" value={task.completionPercent} disabled={!store.perms.canUpdateProgress(task)} onChange={(event) => void store.updateProgress(task.id, Number(event.target.value))} className="mt-2 w-full accent-[var(--dw-color-brand-primary)]" /></div><div className="mt-4 space-y-2">{store.perms.canMarkReadyForReview(task) && <Button className="w-full" onClick={() => void store.changeTaskStatus(task.id, 'ready_for_review')}>Submit for review</Button>}{store.perms.canApproveTask(task) && <Button className="w-full" onClick={() => void store.changeTaskStatus(task.id, 'completed')}><Check className="size-4" /> Approve task</Button>}{store.perms.canReturnForRevision(task) && <Button variant="secondary" className="w-full" onClick={() => void store.changeTaskStatus(task.id, 'needs_revision')}>Return for revision</Button>}</div></section>
          <section className="rounded-2xl border border-[var(--dw-color-border-default)] bg-[var(--dw-color-surface-base)] p-4 shadow-[var(--dw-shadow-sm)]"><h2 className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-[var(--dw-color-ink-tertiary)]"><Paperclip className="size-4" /> Attachments</h2><div className="mt-3 space-y-2">{task.attachments.length ? task.attachments.map((attachment) => <button key={attachment.id} type="button" className="flex w-full items-center gap-2 rounded-xl border border-[var(--dw-color-border-default)] p-2.5 text-left hover:bg-[var(--dw-color-surface-sunken)]"><FileText className="size-4 text-blue-500" /><span className="min-w-0 flex-1"><span className="block truncate text-xs font-semibold text-[var(--dw-color-ink-primary)]">{attachment.name}</span><span className="text-[9px] text-[var(--dw-color-ink-tertiary)]">{attachment.size}</span></span></button>) : <p className="py-3 text-center text-xs text-[var(--dw-color-ink-tertiary)]">No attachments</p>}</div></section>
          <section className="rounded-2xl border border-[var(--dw-color-border-default)] bg-[var(--dw-color-surface-base)] p-4 shadow-[var(--dw-shadow-sm)]"><h2 className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-[var(--dw-color-ink-tertiary)]"><Activity className="size-4" /> Activity</h2><div className="mt-3 space-y-3 border-l border-[var(--dw-color-border-default)] pl-4">{task.activityTimeline.slice().reverse().map((item) => <div key={item.id} className="relative"><span className="absolute -left-[19px] top-1 size-2 rounded-full bg-[var(--dw-color-brand-primary)] ring-2 ring-[var(--dw-color-surface-base)]" /><p className="text-[10px] text-[var(--dw-color-ink-secondary)]"><strong>{item.userName}</strong> {item.action} {item.detail}</p><p className="mt-0.5 text-[9px] text-[var(--dw-color-ink-tertiary)]">{new Date(item.timestamp).toLocaleDateString('en-PK', { dateStyle: 'medium' })}</p></div>)}</div></section>
        </aside>
      </div>
      <TaskFormModal isOpen={store.isFormOpen} onClose={store.closeForm} editingTask={store.editingTask} defaultDate={task.startDate} store={store} perms={store.perms} />
    </PageContainer>
  )
}
