import { useEffect, useMemo, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { ArrowLeft, CheckSquare, Crown, FileText, FolderOpen, MessageSquare, Plus, Send, Settings2, Trash2, UserPlus, UsersRound } from 'lucide-react'
import { PageContainer } from '@/shared/components/layouts'
import { Button } from '@/shared/components/ui/button'
import { Skeleton } from '@/shared/components/ui/skeleton'
import { ErrorState } from '@/shared/components/premium'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/shared/components/ui/dialog'
import { Input } from '@/shared/components/ui/input'
import { cn } from '@/shared/lib/utils'
import { useAuth } from '@/shared/hooks/use-auth'
import { useTeamsStore } from '../hooks/use-teams-store'
import { TeamFormModal } from '../components/team-form-modal'
import { CALENDAR_PEOPLE, getPerson, MOCK_CALENDAR_TASKS } from '@/features/calendar/data/calendar.mock'
import { MOCK_DOCUMENTS } from '@/features/documents/data/documents.mock'
import { STATUS_CONFIG } from '@/features/calendar/types/calendar.types'

type Tab = 'feed' | 'members' | 'tasks' | 'documents'
interface Post { id: string; authorId: string; author: string; initials: string; content: string; createdAt: string }

export function TeamSpacePage() {
  const { id } = useParams()
  const navigate = useNavigate()
  const { user } = useAuth()
  const store = useTeamsStore()
  const [tab, setTab] = useState<Tab>('feed')
  const [postText, setPostText] = useState('')
  const [posts, setPosts] = useState<Post[]>([])
  const [addOpen, setAddOpen] = useState(false)
  const [newMemberId, setNewMemberId] = useState('')
  const [newMemberRole, setNewMemberRole] = useState('Member')
  const team = store.teams.find((item) => item.id === id)

  useEffect(() => { if (!id) return; try { setPosts(JSON.parse(localStorage.getItem(`dw_team_posts_${id}`) ?? '[]') as Post[]) } catch { setPosts([]) } }, [id])
  const teamTasks = useMemo(() => team ? MOCK_CALENDAR_TASKS.filter((task) => team.members.some((member) => member.employeeId === task.assignedToId)).slice(0, 8) : [], [team])
  const teamDocuments = useMemo(() => team ? MOCK_DOCUMENTS.filter((document) => document.tags.some((tag) => team.name.toLowerCase().includes(tag.toLowerCase()) || tag.toLowerCase().includes(team.name.split(' ')[0].toLowerCase()))).slice(0, 6) : [], [team])

  if (store.isLoading) return <PageContainer><Skeleton className="h-52 rounded-2xl" /><Skeleton className="mt-4 h-[500px] rounded-2xl" /></PageContainer>
  if (!team) return <PageContainer><ErrorState title="Team not found" description="This team may have been removed or is unavailable." action={<Button onClick={() => navigate('/teams')}><ArrowLeft className="size-4" /> Back to teams</Button>} /></PageContainer>

  const manager = getPerson(team.managerId)
  const available = CALENDAR_PEOPLE.filter((person) => !team.members.some((member) => member.employeeId === person.id))
  const publishPost = () => { const content = postText.trim(); if (!content || !user) return; const next = [{ id: `post_${Date.now()}`, authorId: user.id, author: `${user.firstName} ${user.lastName}`, initials: `${user.firstName[0]}${user.lastName[0]}`, content, createdAt: new Date().toISOString() }, ...posts]; setPosts(next); localStorage.setItem(`dw_team_posts_${team.id}`, JSON.stringify(next)); setPostText('') }

  return (
    <PageContainer>
      <button type="button" onClick={() => navigate('/teams')} className="mb-4 flex items-center gap-1.5 text-xs font-semibold text-[var(--dw-color-ink-tertiary)] hover:text-[var(--dw-color-brand-primary)]"><ArrowLeft className="size-4" /> Teams / {team.name}</button>
      <header className="relative mb-4 overflow-hidden rounded-2xl border border-[var(--dw-color-border-default)] bg-[var(--dw-color-surface-base)] p-5 shadow-[var(--dw-shadow-sm)]"><div className="absolute inset-x-0 top-0 h-1.5" style={{ background: team.color }} /><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><span className="flex size-16 shrink-0 items-center justify-center rounded-2xl" style={{ background: `${team.color}18`, color: team.color }}><UsersRound className="size-7" /></span><div className="min-w-0 flex-1"><h1 className="text-2xl font-black text-[var(--dw-color-ink-primary)]">{team.name}</h1><p className="mt-1 max-w-2xl text-sm text-[var(--dw-color-ink-secondary)]">{team.description}</p><div className="mt-2 flex flex-wrap gap-2 text-[10px] font-semibold text-[var(--dw-color-ink-tertiary)]"><span>{team.members.length} members</span><span>·</span><span className="flex items-center gap-1"><Crown className="size-3 text-amber-500" />{manager?.name ?? 'No manager'}</span><span>·</span><span>{teamTasks.length} active tasks</span></div></div>{store.perms.canEditTeam(team) && <Button variant="secondary" onClick={() => store.openEditForm(team)}><Settings2 className="size-4" /> Team settings</Button>}</div></header>
      <div className="overflow-hidden rounded-2xl border border-[var(--dw-color-border-default)] bg-[var(--dw-color-surface-base)] shadow-[var(--dw-shadow-sm)]"><div className="flex overflow-x-auto border-b border-[var(--dw-color-border-default)] px-3">{([{ id: 'feed', label: 'Feed', icon: MessageSquare }, { id: 'members', label: `Members (${team.members.length})`, icon: UsersRound }, { id: 'tasks', label: `Tasks (${teamTasks.length})`, icon: CheckSquare }, { id: 'documents', label: `Documents (${teamDocuments.length})`, icon: FolderOpen }] as { id: Tab; label: string; icon: typeof MessageSquare }[]).map((item) => { const Icon = item.icon; return <button key={item.id} type="button" onClick={() => setTab(item.id)} className={cn('flex h-12 shrink-0 items-center gap-2 border-b-2 px-3 text-xs font-semibold', tab === item.id ? 'border-[var(--dw-color-brand-primary)] text-[var(--dw-color-brand-primary)]' : 'border-transparent text-[var(--dw-color-ink-tertiary)]')}><Icon className="size-4" />{item.label}</button> })}</div>
        <div className="p-4 sm:p-6">
          {tab === 'feed' && <div className="mx-auto max-w-3xl"><div className="rounded-2xl border border-[var(--dw-color-border-default)] bg-[var(--dw-color-surface-sunken)]/40 p-3"><div className="flex gap-3"><span className="flex size-9 shrink-0 items-center justify-center rounded-full bg-[var(--dw-color-brand-primary)] text-[10px] font-bold text-white">{user ? `${user.firstName[0]}${user.lastName[0]}` : 'ME'}</span><textarea value={postText} onChange={(event) => setPostText(event.target.value)} placeholder={`Share an update with ${team.name}…`} className="min-h-20 min-w-0 flex-1 resize-none bg-transparent text-sm text-[var(--dw-color-ink-primary)] outline-none placeholder:text-[var(--dw-color-ink-tertiary)]" /></div><div className="mt-2 flex justify-end"><Button size="sm" onClick={publishPost} disabled={!postText.trim()}><Send className="size-4" /> Post update</Button></div></div><div className="mt-4 space-y-3">{posts.length ? posts.map((post) => <article key={post.id} className="rounded-2xl border border-[var(--dw-color-border-default)] p-4"><div className="flex gap-3"><span className="flex size-9 shrink-0 items-center justify-center rounded-full bg-[var(--dw-color-brand-primary)] text-[10px] font-bold text-white">{post.initials}</span><div className="min-w-0 flex-1"><div className="flex items-center justify-between"><p className="text-xs font-bold text-[var(--dw-color-ink-primary)]">{post.author}</p><p className="text-[9px] text-[var(--dw-color-ink-tertiary)]">{new Date(post.createdAt).toLocaleString('en-PK', { dateStyle: 'medium', timeStyle: 'short' })}</p></div><p className="mt-2 whitespace-pre-wrap text-sm leading-relaxed text-[var(--dw-color-ink-secondary)]">{post.content}</p></div></div></article>) : <div className="py-14 text-center"><MessageSquare className="mx-auto size-8 text-[var(--dw-color-ink-tertiary)]" /><p className="mt-3 text-sm font-bold text-[var(--dw-color-ink-secondary)]">Start the team feed</p><p className="mt-1 text-xs text-[var(--dw-color-ink-tertiary)]">Share the first update, decision, or announcement.</p></div>}</div></div>}

          {tab === 'members' && <div><div className="mb-4 flex items-center justify-between"><div><h2 className="text-base font-bold text-[var(--dw-color-ink-primary)]">Team roster</h2><p className="text-xs text-[var(--dw-color-ink-tertiary)]">Roles and membership for this team.</p></div>{store.perms.canManageTeams && <Button size="sm" onClick={() => setAddOpen(true)} disabled={!available.length}><UserPlus className="size-4" /> Add member</Button>}</div><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{team.members.map((member) => { const person = getPerson(member.employeeId); if (!person) return null; const isManager = team.managerId === member.employeeId; return <div key={member.employeeId} className="group flex items-center gap-3 rounded-xl border border-[var(--dw-color-border-default)] p-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl text-xs font-bold text-white" style={{ background: person.avatarColor }}>{person.initials}</span><div className="min-w-0 flex-1"><p className="flex items-center gap-1 truncate text-xs font-bold text-[var(--dw-color-ink-primary)]">{person.name}{isManager && <Crown className="size-3 text-amber-500" />}</p><p className="truncate text-[10px] text-[var(--dw-color-ink-tertiary)]">{isManager ? 'Manager' : member.role} · {person.department}</p></div>{store.perms.canManageTeams && !isManager && <button type="button" onClick={() => { if (window.confirm(`Remove ${person.name} from this team?`)) void store.removeMember(team.id, member.employeeId) }} className="opacity-100 sm:opacity-0 sm:group-hover:opacity-100"><Trash2 className="size-4 text-red-400" /></button>}</div> })}</div></div>}

          {tab === 'tasks' && <div><h2 className="text-base font-bold text-[var(--dw-color-ink-primary)]">Shared team tasks</h2><div className="mt-4 space-y-2">{teamTasks.length ? teamTasks.map((task) => { const assignee = getPerson(task.assignedToId); const status = STATUS_CONFIG[task.status]; return <button key={task.id} type="button" onClick={() => navigate(`/tasks/${task.id}`)} className="flex w-full flex-col gap-3 rounded-xl border border-[var(--dw-color-border-default)] p-3 text-left hover:bg-[var(--dw-color-surface-sunken)] sm:flex-row sm:items-center"><span className={cn('rounded-full px-2 py-1 text-[9px] font-bold', status.bg, status.color)}>{status.label}</span><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold text-[var(--dw-color-ink-primary)]">{task.title}</p><p className="text-[10px] text-[var(--dw-color-ink-tertiary)]">{assignee?.name} · Due {new Date(task.dueDate).toLocaleDateString('en-PK', { dateStyle: 'medium' })}</p></div><span className="text-xs font-bold text-[var(--dw-color-brand-primary)]">{task.completionPercent}%</span></button> }) : <p className="py-10 text-center text-xs text-[var(--dw-color-ink-tertiary)]">No team tasks available.</p>}</div></div>}

          {tab === 'documents' && <div><div className="flex items-center justify-between"><div><h2 className="text-base font-bold text-[var(--dw-color-ink-primary)]">Shared documents</h2><p className="text-xs text-[var(--dw-color-ink-tertiary)]">Files related to this team.</p></div><Button variant="secondary" size="sm" onClick={() => navigate('/documents')}>Open library</Button></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{teamDocuments.length ? teamDocuments.map((document) => <button key={document.id} type="button" onClick={() => navigate('/documents')} className="flex items-center gap-3 rounded-xl border border-[var(--dw-color-border-default)] p-3 text-left hover:bg-[var(--dw-color-surface-sunken)]"><span className="flex size-10 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><FileText className="size-5" /></span><span className="min-w-0"><span className="block truncate text-xs font-bold text-[var(--dw-color-ink-primary)]">{document.name}</span><span className="text-[9px] uppercase text-[var(--dw-color-ink-tertiary)]">{document.extension} · v{document.version}</span></span></button>) : <div className="col-span-full py-10 text-center"><FolderOpen className="mx-auto size-8 text-[var(--dw-color-ink-tertiary)]" /><p className="mt-2 text-xs text-[var(--dw-color-ink-tertiary)]">No team documents yet.</p></div>}</div></div>}
        </div>
      </div>

      <Dialog open={addOpen} onOpenChange={setAddOpen}><DialogContent><DialogHeader><DialogTitle>Add team member</DialogTitle><DialogDescription>Select a directory member and define their role in {team.name}.</DialogDescription></DialogHeader><div className="max-h-56 space-y-1 overflow-y-auto">{available.map((person) => <button key={person.id} type="button" onClick={() => { setNewMemberId(person.id); setNewMemberRole(person.jobTitle) }} className={cn('flex w-full items-center gap-3 rounded-xl border p-2.5 text-left', newMemberId === person.id ? 'border-[var(--dw-color-brand-primary)] bg-[var(--dw-color-brand-primary-muted)]' : 'border-[var(--dw-color-border-default)]')}><span className="flex size-8 items-center justify-center rounded-lg text-[10px] font-bold text-white" style={{ background: person.avatarColor }}>{person.initials}</span><span><span className="block text-xs font-bold text-[var(--dw-color-ink-primary)]">{person.name}</span><span className="text-[10px] text-[var(--dw-color-ink-tertiary)]">{person.department}</span></span></button>)}</div>{newMemberId && <label className="space-y-1.5 text-xs font-semibold text-[var(--dw-color-ink-secondary)]">Team role<Input value={newMemberRole} onChange={(event) => setNewMemberRole(event.target.value)} /></label>}<DialogFooter><Button variant="ghost" onClick={() => setAddOpen(false)}>Cancel</Button><Button disabled={!newMemberId} onClick={() => { void store.addMember(team.id, { employeeId: newMemberId, role: newMemberRole || 'Member' }); setAddOpen(false); setNewMemberId('') }}><Plus className="size-4" /> Add to team</Button></DialogFooter></DialogContent></Dialog>
      <TeamFormModal isOpen={store.isFormOpen} onClose={store.closeForm} editingTeam={store.editingTeam} onCreate={store.createTeam} onUpdate={store.updateTeam} />
    </PageContainer>
  )
}
