import { useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { ArrowLeft, Briefcase, Building2, CalendarDays, Clock3, FileText, Mail, MapPin, Pencil, Phone, ShieldCheck, UsersRound } from 'lucide-react'
import { PageContainer } from '@/shared/components/layouts'
import { Button } from '@/shared/components/ui/button'
import { Skeleton } from '@/shared/components/ui/skeleton'
import { ErrorState } from '@/shared/components/premium'
import { cn } from '@/shared/lib/utils'
import { useEmployeesStore } from '../hooks/use-employees-store'
import { EmployeeFormModal } from '../components/employee-form-modal'
import { EMPLOYEE_ROLE_CONFIG, EMPLOYEE_STATUS_CONFIG, employeeFullName, employeeInitials } from '../types/employee.types'
import { MOCK_TEAMS } from '@/features/teams/data/teams.mock'
import { MOCK_DOCUMENTS } from '@/features/documents/data/documents.mock'

type Tab = 'overview' | 'employment' | 'documents' | 'activity'

export function EmployeeProfilePage() {
  const { id } = useParams()
  const navigate = useNavigate()
  const store = useEmployeesStore()
  const [tab, setTab] = useState<Tab>('overview')
  const employee = store.employees.find((item) => item.id === id)

  if (store.isLoading) return <PageContainer><Skeleton className="h-52 rounded-2xl" /><div className="mt-4 grid gap-4 lg:grid-cols-[300px_1fr]"><Skeleton className="h-96 rounded-2xl" /><Skeleton className="h-96 rounded-2xl" /></div></PageContainer>
  if (!employee) return <PageContainer><ErrorState title="Employee not found" description="This profile may have been removed or you may not have access." action={<Button onClick={() => navigate('/employees')}><ArrowLeft className="size-4" /> Back to employees</Button>} /></PageContainer>

  const role = EMPLOYEE_ROLE_CONFIG[employee.role]
  const status = EMPLOYEE_STATUS_CONFIG[employee.status]
  const teams = MOCK_TEAMS.filter((team) => team.members.some((member) => member.employeeId === employee.id))
  const documents = MOCK_DOCUMENTS.filter((document) => document.owner.initials === employeeInitials(employee)).slice(0, 4)
  const tenureMonths = Math.max(1, Math.round((Date.now() - new Date(employee.joinDate).getTime()) / 2629800000))

  return (
    <PageContainer>
      <button type="button" onClick={() => navigate('/employees')} className="mb-4 flex items-center gap-1.5 text-xs font-semibold text-[var(--dw-color-ink-tertiary)] hover:text-[var(--dw-color-brand-primary)]"><ArrowLeft className="size-4" /> Employees / {employeeFullName(employee)}</button>
      <div className="relative mb-4 overflow-hidden rounded-2xl border border-[var(--dw-color-border-default)] bg-[var(--dw-color-surface-base)] p-5 shadow-[var(--dw-shadow-sm)]"><div className="absolute inset-x-0 top-0 h-1.5" style={{ background: `linear-gradient(90deg, ${employee.avatarColor}, ${role.accent})` }} /><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><span className="flex size-20 shrink-0 items-center justify-center rounded-3xl text-xl font-bold text-white shadow-lg" style={{ background: `linear-gradient(135deg, ${employee.avatarColor}, ${role.accent})` }}>{employeeInitials(employee)}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-black text-[var(--dw-color-ink-primary)]">{employeeFullName(employee)}</h1><span className={cn('rounded-full border px-2 py-0.5 text-[10px] font-bold', status.chip)}>{status.label}</span></div><p className="mt-1 text-sm text-[var(--dw-color-ink-secondary)]">{employee.jobTitle} · {employee.department}</p><div className="mt-2 flex flex-wrap gap-2"><span className={cn('rounded-full border px-2 py-1 text-[10px] font-bold', role.chip)}>{role.icon} {role.label}</span><span className="rounded-full bg-[var(--dw-color-surface-sunken)] px-2 py-1 text-[10px] font-semibold text-[var(--dw-color-ink-tertiary)]">ID: {employee.id}</span></div></div>{store.perms.canEdit(employee) && <Button variant="secondary" onClick={() => store.openEditForm(employee)}><Pencil className="size-4" /> Edit profile</Button>}</div></div>

      <div className="grid gap-4 lg:grid-cols-[300px_minmax(0,1fr)]">
        <aside className="h-fit rounded-2xl border border-[var(--dw-color-border-default)] bg-[var(--dw-color-surface-base)] p-4 shadow-[var(--dw-shadow-sm)] lg:sticky lg:top-24"><h2 className="text-xs font-bold uppercase tracking-wider text-[var(--dw-color-ink-tertiary)]">Contact & work</h2><div className="mt-3 space-y-1">{[{ icon: Mail, label: 'Email', value: employee.email }, { icon: Phone, label: 'Phone', value: employee.phone }, { icon: MapPin, label: 'Location', value: employee.location }, { icon: Building2, label: 'Department', value: employee.department }, { icon: Briefcase, label: 'Job title', value: employee.jobTitle }, { icon: CalendarDays, label: 'Joined', value: new Date(employee.joinDate).toLocaleDateString('en-PK', { dateStyle: 'medium' }) }].map((item) => { const Icon = item.icon; return <div key={item.label} className="flex items-center gap-3 rounded-xl p-2.5 hover:bg-[var(--dw-color-surface-sunken)]"><span className="flex size-8 shrink-0 items-center justify-center rounded-lg bg-[var(--dw-color-brand-primary-muted)]"><Icon className="size-4 text-[var(--dw-color-brand-primary)]" /></span><div className="min-w-0"><p className="text-[9px] uppercase tracking-wide text-[var(--dw-color-ink-tertiary)]">{item.label}</p><p className="truncate text-xs font-semibold text-[var(--dw-color-ink-primary)]">{item.value}</p></div></div> })}</div></aside>

        <section className="min-w-0 overflow-hidden rounded-2xl border border-[var(--dw-color-border-default)] bg-[var(--dw-color-surface-base)] shadow-[var(--dw-shadow-sm)]"><div className="flex overflow-x-auto border-b border-[var(--dw-color-border-default)] px-3">{(['overview','employment','documents','activity'] as Tab[]).map((item) => <button key={item} type="button" onClick={() => setTab(item)} className={cn('h-12 shrink-0 border-b-2 px-3 text-xs font-semibold capitalize', tab === item ? 'border-[var(--dw-color-brand-primary)] text-[var(--dw-color-brand-primary)]' : 'border-transparent text-[var(--dw-color-ink-tertiary)]')}>{item}</button>)}</div><div className="p-4 sm:p-6">
          {tab === 'overview' && <div><h2 className="text-base font-bold text-[var(--dw-color-ink-primary)]">Employee overview</h2><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{[{ label: 'Tenure', value: tenureMonths >= 12 ? `${Math.floor(tenureMonths / 12)}y ${tenureMonths % 12}m` : `${tenureMonths}m` }, { label: 'Teams', value: teams.length }, { label: 'Documents', value: documents.length }, { label: 'Attendance', value: '96%' }].map((stat) => <div key={stat.label} className="rounded-xl border border-[var(--dw-color-border-default)] bg-[var(--dw-color-surface-sunken)]/50 p-3"><p className="text-lg font-black text-[var(--dw-color-ink-primary)]">{stat.value}</p><p className="text-[10px] font-semibold text-[var(--dw-color-ink-tertiary)]">{stat.label}</p></div>)}</div><h3 className="mt-6 text-xs font-bold uppercase tracking-wider text-[var(--dw-color-ink-tertiary)]">Team memberships</h3><div className="mt-2 grid gap-2 sm:grid-cols-2">{teams.length ? teams.map((team) => <button key={team.id} type="button" onClick={() => navigate(`/teams/${team.id}`)} className="flex items-center gap-3 rounded-xl border border-[var(--dw-color-border-default)] p-3 text-left hover:bg-[var(--dw-color-surface-sunken)]"><span className="flex size-9 items-center justify-center rounded-lg" style={{ background: `${team.color}18` }}><UsersRound className="size-4" style={{ color: team.color }} /></span><span><span className="block text-xs font-bold text-[var(--dw-color-ink-primary)]">{team.name}</span><span className="text-[10px] text-[var(--dw-color-ink-tertiary)]">{team.members.find((member) => member.employeeId === employee.id)?.role}</span></span></button>) : <p className="text-xs text-[var(--dw-color-ink-tertiary)]">Not assigned to a team.</p>}</div></div>}
          {tab === 'employment' && <div><h2 className="text-base font-bold text-[var(--dw-color-ink-primary)]">Employment details</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{[{ label: 'Employment status', value: status.label }, { label: 'Account role', value: role.label }, { label: 'Department', value: employee.department }, { label: 'Primary location', value: employee.location }, { label: 'Join date', value: new Date(employee.joinDate).toLocaleDateString('en-PK', { dateStyle: 'long' }) }, { label: 'Last updated', value: new Date(employee.updatedAt).toLocaleDateString('en-PK', { dateStyle: 'medium' }) }].map((item) => <div key={item.label} className="rounded-xl border border-[var(--dw-color-border-default)] p-3"><p className="text-[9px] font-bold uppercase tracking-wide text-[var(--dw-color-ink-tertiary)]">{item.label}</p><p className="mt-1 text-sm font-semibold text-[var(--dw-color-ink-primary)]">{item.value}</p></div>)}</div><div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4"><p className="flex items-center gap-2 text-sm font-bold text-emerald-800"><ShieldCheck className="size-4" /> Employment record verified</p><p className="mt-1 text-xs text-emerald-700">Core account and employment fields are synchronized with the directory.</p></div></div>}
          {tab === 'documents' && <div><h2 className="text-base font-bold text-[var(--dw-color-ink-primary)]">Documents</h2><div className="mt-4 space-y-2">{documents.length ? documents.map((document) => <div key={document.id} className="flex items-center gap-3 rounded-xl border border-[var(--dw-color-border-default)] p-3"><span className="flex size-9 items-center justify-center rounded-lg bg-blue-50 text-blue-600"><FileText className="size-4" /></span><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold text-[var(--dw-color-ink-primary)]">{document.name}</p><p className="text-[10px] uppercase text-[var(--dw-color-ink-tertiary)]">{document.extension} · Version {document.version}</p></div></div>) : <p className="rounded-xl bg-[var(--dw-color-surface-sunken)] p-5 text-center text-xs text-[var(--dw-color-ink-tertiary)]">No owned documents in the current workspace.</p>}</div></div>}
          {tab === 'activity' && <div><h2 className="text-base font-bold text-[var(--dw-color-ink-primary)]">Recent activity</h2><div className="mt-4 space-y-4 border-l border-[var(--dw-color-border-default)] pl-5">{[{ title: 'Profile reviewed', detail: 'Employment information verified by HR', time: 'Today' }, { title: 'Directory profile updated', detail: `Updated ${new Date(employee.updatedAt).toLocaleDateString('en-PK')}`, time: 'Recently' }, { title: 'Joined DreamWeavers', detail: `${employee.jobTitle} · ${employee.department}`, time: new Date(employee.joinDate).toLocaleDateString('en-PK') }].map((item) => <div key={item.title} className="relative"><span className="absolute -left-[25px] top-1 size-2.5 rounded-full bg-[var(--dw-color-brand-primary)] ring-4 ring-[var(--dw-color-surface-base)]" /><p className="text-xs font-bold text-[var(--dw-color-ink-primary)]">{item.title}</p><p className="mt-0.5 text-xs text-[var(--dw-color-ink-secondary)]">{item.detail}</p><p className="mt-1 flex items-center gap-1 text-[9px] text-[var(--dw-color-ink-tertiary)]"><Clock3 className="size-3" />{item.time}</p></div>)}</div></div>}
        </div></section>
      </div>
      <EmployeeFormModal open={store.isFormOpen} onClose={store.closeForm} editingEmployee={store.editingEmployee} assignableRoles={store.perms.assignableRoles} isSaving={store.isSaving} onSubmit={(data) => { if (store.editingEmployee) void store.updateEmployee(store.editingEmployee.id, data) }} />
    </PageContainer>
  )
}
